### ISSUE TITLE
Parsing POST data

### ISSUE THREAD

**Issue by pakozm** [raksoras/luaw#2]
Hi, I was unable to locate documentation about how to parse data received via POST method. I need to pass a file and some text inputs to a Luaw application, but I don't know if there is a standard way in Luaw to parse the received body into a Lua table.
Thanks

**Comment by raksoras** [comment]
Form fields posted via HTTP POST as well as query params through HTTP GET are parsed and are available in req.params object. (req is passed in as a first argument to your handler function). Unfortunately multipart file is yet not implemented in Luaw so file upload is not yet supported. It's on my todo list for next release.

**Comment by raksoras** [comment]
Here is a rudimentary sample code that shows how to handle multi-valued parameter ("name" in this example)
```lua
-- handler to show form
GET 'showform' {
	function(req, resp, pathParams)
	    return [[
		<html>
		<head/>
		<body>
			<form method='POST' action='/myapp/subform'>
				<input type="text" name="name" value="raksoras"/>
				<input type="text" name="name" value="lua"/>
				<input type="text" name="address" value="SFO"/>
				<input type="submit" value="Submit">
			</form>
		</body>
		</html>]]
	end
}

-- handler to process form submission
POST 'subform' {
	function(req, resp, pathParams)
		local buffer = {}
		for k,v in pairs(req.params) do
			table.insert(buffer, k)
			table.insert(buffer, "=")
			if (type(v) == 'table') then
			    table.insert(buffer, table.concat(v, ","))
			else
    			table.insert(buffer, v)
    		end
			table.insert(buffer, " ")
		end
		return table.concat(buffer)
	end
}

**Comment by pakozm** [comment]
If you don't mind, I would like to help writing this part. I'm looking the API of NodeJS and the specification of multipart/form-data. We can discuss how do you think it can be written into current code base.

As a first idea, I think it is possible to parse the body of multipart-data into two tables:
- `req.params` with the same data as you shown in your example.
- `req.files` with the information related to uploaded files. Every file would be indexed by the name
   given in the form, containing as value a table with the `path` where the file has been stored (a 
  os.tmpname() file), `name` with the original filename or nil, `size` with the size of the file in bytes, `type` with the mime type or nil.

This can be done in Lua, just using Lua string patterns. In case do you want to write this yourself, don't hesitate to tell me. In this case I would prepare a function for my webapp to do a limited parsing of only my specific needs.

**Comment by pakozm** [comment]
Finally, I have prepared a multipart parser for my webapp. If you think it can be useful in its current state, I can adapt it to be more coherent with code style in Luaw. Find it in the [following link](https://github.com/pakozm/april-ann-webapps/blob/master/lib/multipart.lua)

**Comment by raksoras** [comment]
Thanks for offering to help! Much appreciated. I can use all the help I can get :)

One thing that caused me to defer multipart-file handling was I was not sure how to handle the uploaded file's content. It's not safe to buffer them in memory as it can be huge and writing to file on a local disc is tricky. I can't really use Lua's normal IO library as it is blocking - a write to temp file on local disc could block entire Luaw server. Ideally I should expose some nonblocking read/write operations from my C code using libuv's async read/write primitives and then multipart parser could use that.

Let me take a look at your code and if it works I'll merge it in. Thanks again for your contribution!

**Comment by pakozm** [comment]
Nice! So, don't precipate :-) I'm aware of your concern about the blocking I/O. Indeed, the code I have written for my demo is suffering this problem if the files are large enough. Let me study the libuv IO library and your C code, I can write a binding of necessary primitives, and review the multipart parser by using your thread scheduler. I would do this in my fork of Luaw, adapt the code comestics as much as possible, and propose the pull request. Probably I would make the pull request before al the changes were made just to move this dicussion there. Let me think about it.
Keep in touch!

**Comment by raksoras** [comment]
I have got to work on it little bit over the weekend. I took your multipart parser and changed it so that it becomes a streaming parser, that is it does not need to read entire request body in memory before it can parse the multi-parts. I thought it was crucial since user can potentially upload huge file(s) and it should not blow up app server memory. I had to ditch regular expression based parsing because streaming parsing means I may have incomplete part during my parsing attempt.

The implementation is checked in branch luaw_11 which I'll merge in few weeks to main. The multipart parser is now integrated with rest of the Luaw HTTP parsing engine. If after parsing headers if the HTTP request is determined to be multipart request (by examining 'Content-Type' header) Luaw HTTP request parters defers reading HTTP request body further and passes the request object to matched request handler. The handler can then "pull" the parts in multipart request in streaming fashion. Here is a sample code:

```lua
local function append(buffer, str)
    if (str) then
        table.insert(buffer, str)
        table.insert(buffer, ", ")
    end
end

POST 'filesupload' {
	function(req, resp, pathParams)
	    if (req:isMultipart()) then
            local token, fieldName, fileName, contentType
            local buffer = {}
            for token, fieldName, fileName, contentType in req:multiPartIterator() do
                append(buffer, token)
                append(buffer, fieldName)
                append(buffer, fileName)
                append(buffer, contentType)
                table.insert(buffer,"\n")
            end
            return table.concat(buffer)
	    end
	    return "Not a multi-part file upload"
	end
}
```

The iterator  returned by req:multiPartIterator() returns tokens "PART_BEGIN", "PART_DATA" and "PART_END" as it progressively pulls different parts of the request. It also returns additional fields like field name, file name and content type with PART_BEGIN and actual part content with PART_DATA. The handler gets exactly one PART_BEGIN and PART_END token returned per part but may get multiple PART_DATA between PART_BEGIN and PART_END for the same part each time returning next content of the same part. The iterator finishes when the request body finishes.

The implementation is in luaw_lib.lua and example handlers are in webapp/myapp/handlers.

Finally, there is still other part of the problem that is yet unfinished - how the handler handles the data it pulled from the request? Most likely handler would want to write it to some sort of temp file in its local directory which means Luaw needs to support non-blocking file IO APIs which are missing at the moment. Hopefully, I'll get some time to add them soon

**Comment by pakozm** [comment]
Sorry, I have been out of office for a while. You have been a very nice work integrating this into Luaw :-)
I think it would be straightforward to integrate the multipart implementation into my web app. I would check that as soon as possible, we are busy currently :(

**Comment by raksoras** [comment]
No worry and no hurry. It's a hobby project after all :)

**Comment by raksoras** [comment]
Latest version of Luaw now support multi-part file uploader

**Comment by pakozm** [comment]
Nice! I has been busy, but I hope to push forward my project using Luaw during June :-)
Thanks!
